In [5]:
import numpy as np
import scipy.io
import torch

In [4]:
path = r"C:\Users\gschmidt\Desktop\subFiles.mat"

mat = scipy.io.loadmat(path)
print(mat['subNights'])

[[ 1.  2.  3.  4.]
 [ 1.  2.  3.  4.]
 [ 1.  2.  3.  4.]
 [ 1.  3.  4.  5.]
 [ 1.  3.  4.  5.]
 [ 1.  2.  3.  4.]
 [ 1.  2.  3.  4.]
 [ 1.  2.  3. nan]
 [nan nan nan nan]
 [ 1.  2.  3.  4.]
 [ 1.  2.  3.  4.]
 [ 1.  2.  3.  4.]]


In [56]:
batch_size, channels, time = 3, 4, 1000
dropout_mask = (torch.rand(batch_size, channels, 1) > 0.1).float()
print(dropout_mask)

tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[0.],
         [1.],
         [0.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]])


In [4]:
montage = np.load(r"C:\Users\gschmidt\BrainDecoding\configs\thingsmeg_montage.npy")

print(montage.shape)

(271, 2)


In [5]:
print(montage)

[[0.4528255  0.59689714]
 [0.4173133  0.57397155]
 [0.37753064 0.55778877]
 [0.33696133 0.53396413]
 [0.30268531 0.5066557 ]
 [0.2747026  0.47193016]
 [0.24818083 0.43068656]
 [0.41225618 0.53227843]
 [0.37314781 0.51575851]
 [0.33954608 0.4900234 ]
 [0.31426049 0.45720833]
 [0.28931205 0.41944853]
 [0.3577517  0.45181407]
 [0.32875756 0.41349237]
 [0.39124105 0.4774368 ]
 [0.36943926 0.41180666]
 [0.4533874  0.52576036]
 [0.43091132 0.4894615 ]
 [0.40000672 0.4367551 ]
 [0.4052886  0.39450008]
 [0.42461802 0.3594374 ]
 [0.45372454 0.4545112 ]
 [0.43641796 0.4184371 ]
 [0.45675881 0.38303728]
 [0.41304284 0.79052854]
 [0.35359362 0.77782955]
 [0.29493107 0.75984869]
 [0.23649327 0.74006975]
 [0.44664458 0.76052297]
 [0.39517436 0.75164492]
 [0.34595176 0.73737262]
 [0.2930206  0.71624511]
 [0.42495516 0.72310031]
 [0.37798017 0.71276131]
 [0.32842042 0.69331951]
 [0.28515397 0.67174248]
 [0.24110086 0.64567023]
 [0.45102741 0.69208332]
 [0.4069743  0.68556526]
 [0.36067359 0.66949487]
